g2qs = { 'Career Opportunities':              (80, 51, 88, 2, 52),
         'Compensation & Benefits':           (18, 53, 73, 86, 4),
         'Coworkers':                         (19, 54, 104, 55, 106),
         'Culture and Climate':               (81, 93, 63, 101),
         'Senior Management Level':           (46, 15, 34, 96, 74),
         'Job Security':                      (110, 21, 36),
         'My Manager/Supervisor':             (67, 45, 97, 37, 60),
         'Organizational Structure':          (1, 38, 72, 39, 24),
         'Recognition':                       (17, 62, 42, 79, 77),
         'Safety & Working Environment':      (9, 82, 47, 10, 31, 48),
         'Team Dynamics':                     (28, 5, 43, 14, 49),
         'Training Opportunities':            (56, 107, 84, 69, 8),
         'Work/Life Balance':                 (66, 20, 71, 85, 50, 102),
         'Workplace Ethics':                  (25, 75, 99, 13, 76),
         'Base Questions':                    (100, 3, 23, 105, 70, 98, 90, 68, 65, 95, 30, 78, 103),
         'County Council':                    (6, 29, 57, 87, 108),
         'Psychologically Healthy Workplace': (32, 59, 61, 91, 10),
         'Custom Questions':                  (58, 94, 64, 11, 89, 40, 26, 22, 16, 7, 41, 27, 92, 33),
         'Committee Added Questions':         (12, 35, 44, 83, 109)}

###invert
##d={}
##for k,v in _d.items():
##  for i in v:
##    d[i]=k

q2g= {1:'Organizational Structure',
      2:'Career Opportunities',
      3:'Base Questions',
      4:'Compensation & Benefits',
      5:'Team Dynamics',
      6:'County Council',
      7:'Custom Questions',
      8:'Training Opportunities',
      9:'Safety & Working Environment',
      10:'Safety & Working Environment',
      11:'Custom Questions',
      12:'Committee Added Questions',
      13:'Workplace Ethics',
      14:'Team Dynamics',
      15:'Senior Management Level',
      16:'Custom Questions',
      17:'Recognition',
      18:'Compensation & Benefits',
      19:'Coworkers',
      20:'Work/Life Balance',
      21:'Job Security',
      22:'Custom Questions',
      23:'Base Questions',
      24:'Organizational Structure',
      25:'Workplace Ethics',
      26:'Custom Questions',
      27:'Custom Questions',
      28:'Team Dynamics',
      29:'County Council',
      30:'Base Questions',
      31:'Safety & Working Environment',
      32:'Psychologically Healthy Workplace',
      33:'Custom Questions',
      34:'Senior Management Level',
      35:'Committee Added Questions',
      36:'Job Security',
      37:'My Manager/Supervisor',
      38:'Organizational Structure',
      39:'Organizational Structure',
      40:'Custom Questions',
      41:'Custom Questions',
      42:'Recognition',
      43:'Team Dynamics',
      44:'Committee Added Questions',
      45:'My Manager/Supervisor',
      46:'Senior Management Level',
      47:'Safety & Working Environment',
      48:'Safety & Working Environment',
      49:'Team Dynamics',
      50:'Work/Life Balance',
      51:'Career Opportunities',
      52:'Career Opportunities',
      53:'Compensation & Benefits',
      54:'Coworkers',
      55:'Coworkers',
      56:'Training Opportunities',
      57:'County Council',
      58:'Custom Questions',
      59:'Psychologically Healthy Workplace',
      60:'My Manager/Supervisor',
      61:'Psychologically Healthy Workplace',
      62:'Recognition',
      63:'Culture and Climate',
      64:'Custom Questions',
      65:'Base Questions',
      66:'Work/Life Balance',
      67:'My Manager/Supervisor',
      68:'Base Questions',
      69:'Training Opportunities',
      70:'Base Questions',
      71:'Work/Life Balance',
      72:'Organizational Structure',
      73:'Compensation & Benefits',
      74:'Senior Management Level',
      75:'Workplace Ethics',
      76:'Workplace Ethics',
      77:'Recognition',
      78:'Base Questions',
      79:'Recognition',
      80:'Career Opportunities',
      81:'Culture and Climate',
      82:'Safety & Working Environment',
      83:'Committee Added Questions',
      84:'Training Opportunities',
      85:'Work/Life Balance',
      86:'Compensation & Benefits',
      87:'County Council',
      88:'Career Opportunities',
      89:'Custom Questions',
      90:'Base Questions',
      91:'Psychologically Healthy Workplace',
      92:'Custom Questions',
      93:'Culture and Climate',
      94:'Custom Questions',
      95:'Base Questions',
      96:'Senior Management Level',
      97:'My Manager/Supervisor',
      98:'Base Questions',
      99:'Workplace Ethics',
      100:'Base Questions',
      101:'Culture and Climate',
      102:'Work/Life Balance',
      103:'Base Questions',
      104:'Coworkers',
      105:'Base Questions',
      106:'Coworkers',
      107:'Training Opportunities',
      108:'County Council',
      109:'Committee Added Questions',
      110:'Job Security'}

assert len(q2g)==110
